class_mapping = {
    0: {'name': 'Apple', 'id': 5367},
    1: {'name': 'Banana', 'id': 5388},
    2: {'name': 'Bellpepper', 'id': 285829},
    3: {'name': 'Carrot', 'id': 6034},
    4: {'name': 'Cucumber', 'id': 6244},
    5: {'name': 'Mango', 'id': 5436},
    6: {'name': 'Orange', 'id': 5271},
    7: {'name': 'Potato', 'id': 5718},
    8: {'name': 'Strawberry', 'id': 5525},
    9: {'name': 'Tomato', 'id': 6138},
    10: {'name': 'Rotten Apple', 'id': 0},
    11: {'name': 'Rotten Banana', 'id': 0},
    12: {'name': 'Rotten Bellpepper', 'id': 0},
    13: {'name': 'Rotten Carrot', 'id': 0},
    14: {'name': 'Rotten Cucumber', 'id': 0},
    15: {'name': 'Rotten Mango', 'id': 0},
    16: {'name': 'Rotten Orange', 'id': 0},
    17: {'name': 'Rotten Potato', 'id': 0},
    18: {'name': 'Rotten Strawberry', 'id': 0},
    19: {'name': 'Rotten Tomato', 'id': 0},
}